const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: " USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
  CREATE_USER_SUCCESS: "SAVE_USER_SUCCESS",
  CREATE_USER_FAILD: "SAVE_USER_FAILD",
  //admin
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAILD: "FETCH_GENDER_FAILD",
  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAILD: "FETCH_ROLE_FAILD",
  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAILD: "FETCH_POSITION_FAILD",
  //get user CRUD redux
  FETCH_GET_USER_SUCCESS: "FETCH_GET_USER_SUCCESS",
  FETCH_GET_USER_FAILD: "FETCH_GET_USER_FAILD",
  //delete User Redux
  DELETE_USER_SUCCESS: " DELETE_USER_SUCCESS",
  DELETE_USER_FAILD: "DELETE_USER_FAILD",
});

export default actionTypes;
